### ISSUE TITLE
WebRTCom client ==>Asterisk==>WebRTCom client :ICE Iissue breaks call

### ISSUE THREAD

**Issue by yassen2gx** [RestComm/webrtcomm#11]
As a new user of this framework,I have this problem:
I am using  Asterisak 13.4.0 pbx,I have been working on a worst-so-far WEB RTC issue for too much longer than I'd actually expected; I am using WebRTComm for my sip client stack and chrome Version 44.0.2403.125 m on both of client boxes as userA and userB resp. I have deployed and set up asterisk for web RTC on a centos 7(x86_64) server runing at "192.168.1.2" with the following sip.conf,extensions.conf,http.conf,rtp.conf:

sip.conf :
[general]
context=guest
localnet=192.168.1.0/255.255.255.0
externrefresh=150
language=en
allowguest=yes
callcounter=yes
allowtransfer=yes
callevents=yes
udpbindaddr=0.0.0.0:5060
transport=udp,ws
limitonpeers=yes
realm=192.168.1.2
nat=force_rport,comedia ;eventhough I am runing everytyhing local.'no' had not effect change
rtcachefriends=yes
disallow=all
allow=alaw
allow=ulaw
allow=gsm
useragent=test-agent

[userA]
host=dynamic
secret=strong pass
context=IncomingRTCCxt
type=friend ;tried user and peer as well
insecure=invite ;helped me avoid 401 auth issue
avpf=yes
dtmf=auto
nat=no
qualify=yes
force_avp=yes
icesupport=yes
encryption=yes
transpport=ws,udp
directmedia=no
disallow=all
allow=alaw
allow=ulaw
allow=gsm
dtlsenable=yes
dtlsverify=no ;tried fingerprint as well
dtlscertfile=/etc/asterisk/keys/asterisk.pem
dtlscafile=/etc/asterisk/keys/ca.crt
dtlsprivatekey=/etc/asterisk/keys/asterisk.pem
dtlssetup=actpass
same for userB (though will be using template later) [userB] ... ;as above

extensions.conf:
exten => userA,1,Dial(SIP/userA,40)
exten => userB,1,Dial(SIP/userB,40)
NOTE: even with:answer(),Playback(hello-world),i get failed to set remote answer sdp...this time answer sdp.but with dial application,it is 'remote offer sdp...'

http.conf:
[general]
enable=yes
bindaddr=0.0.0.0
bindport=8088

rtp.conf:
[general]
rtpstart=10000
rtpend=65000 ;because I realised asterisk was using large ports in my sdp on REGISTER etc..
icesupport=yes ;tried 'true' as well
;stunaddr=stun.l.google.com:19302//disabled to avoid ice connectivity as I am on the internet.

when I call userB from userA, userB rings with the rtp debug: --Executing [userA@IncomingRTCCxt:1] Dial("SIP/userB 0000000","SIP/userA,40") in new stack ==Using SIP/RTP CoS mark 5 ==Called SIP/userB ==SIP/userB-00000001 is ringing

As soon as callee/userB picks up,some endless ICE messages trying to connect to an ice server which is dsiabled at the client (WebRTCom) as null/undefined and at the asterisk side. since I am running all three boxes on my local net I set srvlookup=no,nat=no.I even set localnet=192.168.1.0/255.255.255.0.My realm is 192.168.1.2 defined on both sides (I had also disable stunaddr in rtp.conf too ).this is the latest error:
==chan_sip.c:....ast_sockaddr_resolve:getaddrinfo("xABjhsnyHGS.invalid","null",...):Name or service not known.
==chan_sip.c __setaddress_fromk_contact : invalid host name in contact (can't resolve in dns)'.

The caller keeps ringing and as soon as I pick up,it goes through the ice connection and messages for a while and displays the above messages and the caller keeps calling/ringing and callee hungs up with:local media stream has been ended.both clients are the same WebRTCom instances deployed on the same local server.
Any ideas ?
thanks once again

**Comment by deruelle** [comment]
Please attach the Console Chrome logs of each WebRTComm Client so we can see what's happening on the Chrome side. We don't have any experience in Astersik so if this is an Asterisk issue we won't be able to help out.

**Comment by yassen2gx** [comment]
Hi,
thanks for you response.It was indeed related to a known bug in asterisk
not in webrtcom side.
Nonetheless what is the link to the latest webrtcomm download.I couldn't
find anything good at mobicents.
thanks

sincerely

---
- Sanogo _Abdoul Kader
  *Chief Engineer @ Rootingo Incorporation_

Abidjan, Republic of Ivory Coast (Coté d'Ivoire)
Mobile :
- (+225) 45 196 478 / 02 095 279*Please SMS/Email, in an event of call
  failure !

---

The information contained in this e-mail and any accompanying
materials ,links and other resources are confidential and strictly

## intended for the above address (es) as applicable.

**Comment by deruelle** [comment]
It's recommended to use the master https://github.com/Mobicents/webrtcomm/tree/master/build at the moment.

**Comment by yassen2gx** [comment]
Ok,thanks a lot indeed !!

**Comment by deruelle** [comment]
My pleasure. What are you building exactly ? Any chance it's already live and testable ?

**Comment by yassen2gx** [comment]
Hi,
Not yet and I am sure to come back in touch with you at some stage
later.for now,it is all relatively at early stage.
Thanks

sincerely

---
- Sanogo _Abdoul Kader
  *Chief Engineer @ Rootingo Incorporation_

Abidjan, Republic of Ivory Coast (Coté d'Ivoire)
Mobile :
- (+225) 45 196 478 / 02 095 279*Please SMS/Email, in an event of call
  failure !

---

The information contained in this e-mail and any accompanying
materials ,links and other resources are confidential and strictly

## intended for the above address (es) as applicable.
